// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGaoZhE9reni69EWUynGvA5X-4vYHlxVo',
    appId: '1:1075038264526:web:675972749760c954dac49f',
    messagingSenderId: '1075038264526',
    projectId: 'tulga-biydaalt',
    authDomain: 'tulga-biydaalt.firebaseapp.com',
    storageBucket: 'tulga-biydaalt.firebasestorage.app',
    measurementId: 'G-00T483ZZBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAce8G6o3vq7TvnpXVL5m4uX0Hf6ePX7bI',
    appId: '1:1075038264526:android:e187e96bab2d4af6dac49f',
    messagingSenderId: '1075038264526',
    projectId: 'tulga-biydaalt',
    storageBucket: 'tulga-biydaalt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvbgUBr5E4j4L-LtHYTq19mTOLEoYqaGM',
    appId: '1:1075038264526:ios:f5a702459be50214dac49f',
    messagingSenderId: '1075038264526',
    projectId: 'tulga-biydaalt',
    storageBucket: 'tulga-biydaalt.firebasestorage.app',
    iosBundleId: 'com.example.cloudTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvbgUBr5E4j4L-LtHYTq19mTOLEoYqaGM',
    appId: '1:1075038264526:ios:f5a702459be50214dac49f',
    messagingSenderId: '1075038264526',
    projectId: 'tulga-biydaalt',
    storageBucket: 'tulga-biydaalt.firebasestorage.app',
    iosBundleId: 'com.example.cloudTodoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGaoZhE9reni69EWUynGvA5X-4vYHlxVo',
    appId: '1:1075038264526:web:76bb1572dc85aed2dac49f',
    messagingSenderId: '1075038264526',
    projectId: 'tulga-biydaalt',
    authDomain: 'tulga-biydaalt.firebaseapp.com',
    storageBucket: 'tulga-biydaalt.firebasestorage.app',
    measurementId: 'G-5H63PLP4TM',
  );
}
